x-logging: &default-logging
  driver: json-file
  options:
    max-size: 50m
    max-file: 1

services:
  whoami:
    container_name: whoami
    image: traefik/whoami:v1.10.1
    restart: unless-stopped
